language: cpp
compiler: gcc
dist: xenial

notifications:
  email: false

cache: 
  directories:
    - $TRAVIS_BUILD_DIR/syzygy

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - deadsnakes
          packages:
            - lcov
            - g++-7
            - python3.7-dev

before_install:
  # C++17
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 90
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-7 90

install: 
  - pyenv global $(pyenv whence 2to3)  # activate all python versions
  - pip install pipenv
  - pipenv install --dev --skip-lock

    
  # Install stockfish (used in search verification). Script from https://github.com/niklasf/python-chess/blob/master/.travis.yml
  - wget https://stockfish.s3.amazonaws.com/stockfish-10-linux.zip
  - unzip stockfish-10-linux.zip
  - mkdir -p bin
  - cp stockfish-10-linux/Linux/stockfish_10_x64_modern bin/stockfish
  - chmod +x bin/stockfish
  - export PATH="`pwd`/bin:${PATH}"
  - which stockfish || (echo $PATH && false)

  # Install coverals gem for uploading coverage to coveralls.
  - gem install coveralls-lcov
  
  - bash ci/fetch-tablebase.sh

before_script:
  - lcov --version
  - gcov --version
  - g++ --version
  - PARENTDIR=$(pwd)

script:
  - CMAKE_BUILD_TYPE=Coverage pipenv run python tests/test_search.py
  - cd $PARENTDIR/build
  - make bench  
  - make coverage

after_success:
  - cd $PARENTDIR/build
  - lcov --list coverage_out.info.cleaned  # Show test report in travis log.
  - coveralls-lcov coverage_out.info.cleaned  # uploads to coveralls
  - bash <(curl -s https://codecov.io/bash) -f coverage_out.info.cleaned || echo "Codecov did not collect coverage reports"

