language: cpp
compiler: gcc
dist: xenial

notifications:
  email: false

addons:
  apt:
    sources:
    - deadsnakes
    packages:
    - python3.7-dev

before_install:
  # C++17
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  - pyenv global $(pyenv whence 2to3)  # activate all python versions
  - python3 --version
  - pip3 --version
  - pip3 install python-chess

  # C++17
  - sudo apt-get install -qq g++-7 gcc-7
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 90
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-7 90
   
  # install newer LCOV (apt version outdated and fails for new gcov).
  - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
  - tar xf lcov_1.11.orig.tar.gz
  - sudo make -C lcov-1.11/ install  
  - which lcov 
    
  # Install stockfish (used in search verification). Script from https://github.com/niklasf/python-chess/blob/master/.travis.yml
  - wget https://stockfish.s3.amazonaws.com/stockfish-10-linux.zip
  - unzip stockfish-10-linux.zip
  - mkdir -p bin
  - cp stockfish-10-linux/Linux/stockfish_10_x64_modern bin/stockfish
  - chmod +x bin/stockfish
  - export PATH="`pwd`/bin:${PATH}"
  - which stockfish || (echo $PATH && false)

  # Install coverals gem for uploading coverage to coveralls.
  - gem install coveralls-lcov

before_script:
  - lcov --version
  - gcov --version
  - g++ --version
  - PARENTDIR=$(pwd)

script:
  - CMAKE_BUILD_TYPE=Coverage python3 tests/test_search.py
  - cd $PARENTDIR/build
  - make coverage
  - make bench  # Bench not part of test suite, but provides signature.

after_success:
  - cd $PARENTDIR/build
  - lcov --list coverage_out.info.cleaned  # Show test report in travis log.
  - coveralls-lcov coverage_out.info.cleaned  # uploads to coveralls
  - bash <(curl -s https://codecov.io/bash) -f coverage_out.info.cleaned || echo "Codecov did not collect coverage reports"

