#!/usr/bin/env sh

filename="match-history.pgn"
anchorvalue=2000
anchorname="Goldfish v1.0"
if [ $# -ge 1 ]
  then
      filename="$1"
fi
if [ $# -ge 3 ]
  then
      anchorvalue=$2
      anchorname=$3
fi

ordo -p $filename -a $anchorvalue -A "$anchorname" -W -D -j headtoheadresults > outputsummary

cat headtoheadresults outputsummary

rm headtoheadresults outputsummary
